[package]
name = "image_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.6.4"
actix-files = "0.6.2"
actix-multipart = "0.6.1"
actix-web = "4.4.0"
dotenv = "0.15.0"
futures = "0.3.28"
num_cpus = "1.16.0"

[profile.release]
strip = true
lto = true
codegen-units = 1
